apiVersion: apps/v1
kind: Deployment
metadata:
  name: shard-manager
  namespace: shard-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shard-manager
  template:
    metadata:
      labels:
        app: shard-manager
    spec:
      containers:
        - name: shard-manager
          image: timsmart/effect-cluster:shard-manager
          ports:
            - containerPort: 8080
              name: tcp
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              value: postgres.postgres.svc
            - name: DB_PORT
              value: '5432'
            - name: DB_DATABASE
              value: effect_cluster
            - name: DB_USER
              value: cluster
            - name: DB_PASSWORD
              value: cluster
            - name: SHARD_MANAGER_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
