apiVersion: apps/v1
kind: Deployment
metadata:
  name: runner
  namespace: runner
spec:
  replicas: 5
  selector:
    matchLabels:
      app: runner
  template:
    metadata:
      labels:
        app: runner
    spec:
      containers:
        - name: runner
          image: timsmart/effect-cluster:runner
          ports:
            - containerPort: 34431
              name: tcp
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              value: postgres.postgres.svc
            - name: DB_PORT
              value: '5432'
            - name: DB_DATABASE
              value: effect_cluster
            - name: DB_USER
              value: cluster
            - name: DB_PASSWORD
              value: cluster
            - name: SHARD_MANAGER_HOST
              value: shard-manager.shard-manager.svc
            - name: HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            tcpSocket:
              port: 34431
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 34431
            initialDelaySeconds: 5
            periodSeconds: 10
