apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: gp2
