apiVersion: apps/v1
kind: Deployment
metadata:
  name: battleships
  namespace: battleships
spec:
  replicas: 1
  selector:
    matchLabels:
      app: battleships
  template:
    metadata:
      labels:
        app: battleships
    spec:
      containers:
        - name: battleships
          image: timsmart/effect-cluster:runner
          ports:
            - containerPort: 34431
              name: tcp
          args:
            - node
            - ed-runner.js
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              value: mysql.mysql.svc
            - name: DB_PORT
              value: '3306'
            - name: DB_DATABASE
              value: effect_cluster
            - name: DB_USER
              value: cluster
            - name: DB_PASSWORD
              value: cluster
            - name: SHARD_MANAGER_HOST
              value: shard-manager.shard-manager.svc
            - name: HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            tcpSocket:
              port: 34431
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 34431
            initialDelaySeconds: 5
            periodSeconds: 10
